# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK_Anna_Ershova' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VK_Anna_Ershova
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'RealmSwift'
  pod 'KeyPathKit'

end
